### ISSUE TITLE
Embedd title, author and keywords using ffmpeg

### ISSUE THREAD

**Issue by pke** [gatecrasher777/ytcog#1]
Thanks for this great library!

Do you think it would be possible to embed the keywords, author and title of videos into the generated output file using ffmpeg?

**Comment by gatecrasher777** [comment]
Thanks for your comment and suggestion.  At present, the library produces mp4, webm and mkv containers so it may require a bit of research/experimentation to confirm that ffmpeg's -metadata command works with each container and/or whether there are only specific tags allowed by each container. 

But I can envision adding a metadata field into the video/download options where a user could specify which key value pairs  to embed as metadata in downloaded files.  I'm currently working on a CLI version that requires some changes to the library to allow embedding of specific data into customized filenames, so I will look into this suggestion too.  Watch out for v1.1.0.

**Comment by pke** [comment]
Cool. Was about to do a CLI myself. Waiting now what you come up with.

**Comment by gatecrasher777** [comment]
Still to complete all the coding and testing, but I have worked a bit on the [readme.](https://github.com/gatecrasher777/ytcog-dl) Including the metadata addition, after verifying what will work with ffmpeg -metadata.
