### ISSUE TITLE
Question about NodeJS Streams

### ISSUE THREAD

**Issue by r0hin** [gatecrasher777/ytcog#11]
Instead of downloading a video/audio to a file, is it possible to output the audio into a stream - for example, an ExpressJS response?

Thanks for your help.

**Comment by gatecrasher777** [comment]
Sure, you don't have to video.download() to a file.  
You can do something like this:

```javascript
const web = express();
web.post('/',function(req, res) {
    let video = new ytcog.Video({id: req.body.id});
    await video.fetch();
    if (video.status === 'OK') {
        let inputStream = miniget(video.audioStreams[0].url);
        inputStream.pipe(res);
    } else {
     //handle error
    }
});
```
Which would send the "best" audio stream in response to a post request of a video id.

**Comment by r0hin** [comment]
Ah I see, thank you! One last thing: I've been trying to implement your solution but I am getting error:
`TypeError: Cannot read property 'id' of undefined
    at new Video (/.../server/node_modules/ytcog/lib/video.js:19:21)
    at /.../server/index.js:29:19
`

It is on the line: `const video = new ytcog.Video({id: 'KGLmrdr9hFo'});`

**Comment by gatecrasher777** [comment]
Well, I skipped a few steps. You need to create a session object and pass that to first parameter of new ytcog.Video.  I'll edit the code above.

**Comment by r0hin** [comment]
Yeah, I guess it works differently across browsers. I am using a standard JavaScript fetch and piping the stream directly into an audio element and it seems to load the first couple minutes or so and then stop loading afterwards. Perhaps this is due to some kind of timeout but I'll keep looking into it.
