### ISSUE TITLE
is it possible to return a readable stream when there is no file name given, and support range download?

### ISSUE THREAD

**Issue by ocylib** [gatecrasher777/ytcog#18]
Is it possible to return a readable stream when there is no file name given, and support range download? 
I use to use [node-ytdl-core](https://github.com/fent/node-ytdl-core) before. 
and then find this for ytdl-core face 410 error when deploy to  Heroku

**Comment by gatecrasher777** [comment]
ytcog's current download module streams (video and audio) into files and merges (if necessary) into single file.  It uses ranges to improve performance. But it is essentially a black box running in a separate fork.

Perhaps if you can flesh out your use case (code would be helpful) of ytdl-core, I could look at adding an alternative to video.download that gives programmatic access and control over streams. 

You can still get full access to the download urls after a ```video.fetch()``` via ```video.videoStream[n].url``` and ```video.audioStream[n].url```

**Comment by ocylib** [comment]
@gatecrasher777 I will try to create a class, which extends class Video, and rewrite the download method. the new download method may like downloadfrominfo in ytdl-core
