### ISSUE TITLE
can I get  bigger Video Thumbnail

### ISSUE THREAD

**Issue by ocylib** [gatecrasher777/ytcog#19]
I'd like to play video on the web page, and I need a video thumbnail to be the poster of my video-tag
I tried to get this from```video. data``` after ```await video.fetch()```. I found some thumbnails, but it is small. how can I get a bigger one?
thanks

**Comment by gatecrasher777** [comment]
The one I generally use in my apps is : `https://i.ytimg.com/vi/videoId/hqdefault.jpg` which is 480x360.

Just replace `videoId`  with the actual  `video.id`.

**Comment by ocylib** [comment]
Nice work
