### ISSUE TITLE
Inconsistent Playback (Slow Buffering)

### ISSUE THREAD

**Issue by r0hin** [gatecrasher777/ytcog#24]
I'm sure you already know but thought I'd post here about a recent change YouTube made that affects how videos are parsed. Leads to slow playback.

https://github.com/TeamNewPipe/NewPipeExtractor/pull/785
Here's a referenced [pull](https://github.com/TeamNewPipe/NewPipeExtractor/pull/785) that seemed to help.

Edit: I have also been noticing that some playback URLs simply don't work. I think this is related to this issue since it's only been happening since this change and seems to be in a similar realm. (Links will work upon retrying the video information fetch code.)

Thanks!

**Comment by beauner69** [comment]
I added this PR based off the NewPipe change
https://github.com/gatecrasher777/ytcog/pull/25

**Comment by r0hin** [comment]
Absolutely stunning speed! Thanks both.
