### ISSUE TITLE
debug logs will be logged on console even though debug mode was set the "false"

### ISSUE THREAD

**Issue by gaojie429** [gatecrasher777/ytcog#26]
As the title says, I can't disable debug log. It happened after I update ytcog to v2.3.1.

**Comment by gatecrasher777** [comment]
For most objects ```<object>.debugOn = 'false';``` is the default state, so you should not have to set it unless you want debug info. 

```Download``` in index.js is the only pseudo object that writes directly to console (with download progress) without any reference to debug. Perhaps that is an issue. If so, I can make those console writes subject to the debug parameter as well.

**Comment by gatecrasher777** [comment]
Any more information on this? I can only replicate when using ytcog.dl() method, in which case, the console logs are intended.

**Comment by gaojie429** [comment]
Yes, I use exactly ytcog.dl() to get videos.
I didn't know this console log was intended.

Well then, how can I disable console log?
`debug : false` didn't work for me in this version.

Here is my code.

` 
let options = {
  id: '<ID>',
  path: '<PATH>',
  filename: 'temp',
  container: 'mp4',
  videoQuality: 'none',
  audioQuality: 'highest',
  mediaBitrate: 'highest',
  videoFormat: -1,
  audioFormat: -1,
  metadata: 'author,title,published',
  overwrite: 'yes',
}
await ytcog.dl(options);`

**Comment by gatecrasher777** [comment]
To download silently:

```javascript

        const ytcog = require('ytcog');

	const session = new ytcog.Session();
        await session.fetch();
        const video = new ytcog.Video(session, { 
             id: '<ID>',
             path: '<PATH>',
             filename: 'temp',
             container: 'mp4',
             videoQuality: 'none',
            audioQuality: 'highest',
            mediaBitrate: 'highest',
            videoFormat: -1,
            audioFormat: -1,
            metadata: 'author,title,published',
            overwrite: 'yes',
	});
	await video.download();

```

**Comment by gaojie429** [comment]
I could download videos without any log using this code.
Thank you!
