### ISSUE TITLE
Long delay after download complete

### ISSUE THREAD

**Issue by ikmolbo** [gatecrasher777/ytcog#28]
Hi,

I'm using yt-cog to download audio from Youtube. While the download is fairly quick, if the target audio file is downloaded in 10 seconds (i.e. we see the progress event reach 100%), there's then a further 20-30 seconds where nothing is happening but the script is still waiting for video.download to complete.

Looking at the filesystem, I see the target file created e.g. `sSheoMl5_uQ.aac`, but a secondary file `sSheoMl5_uQ_audio_a0.mp4` is also created and eventually deleted after the long delay. 

Here's the relevant code:

```
  await session.fetch();
  let video = new ytcog.Video(session, {id: req.params.id, videoQuality: 'none', filename: '${id}'});
  await video.fetch();

  let bytesDownloaded = 0;
  await video.download({
      progress: (prog, size, total)=>{
          bytesDownloaded += size;
          process.stdout.write( `Progress ${Math.floor(prog)}%  ${bytesDownloaded}/${total} bytes    \r` );
      } 
  });

  return res.status(200).json({
    message: "Download complete!",
  });
```

Thwe same happens using the dl method:

```
  let options = {
		// any video id, mandatory propery
		id: req.params.id,
		// supply a download folder for downloaded video
		path: './tmp',
		// supply a optional filename, do not include an extension. default filename is author_title_videoId_format.ext
		filename: '${id}',
		// any, mp4, webm, mkv
		container: 'any',
		// desired quality: highest, 1080p, 720p, 480p, medium, 360p, 240p, 144p, lowest, none
		videoQuality: 'none',
		// desired audio quality: high, medium, low, none
		audioQuality: 'medium',
	};

  await ytcog.dl(options);
```

Can you suggest what might be causing the delay?

**Comment by ikmolbo** [comment]
My guess is that yt-cog is running ffmpeg to convert the audio-only file from one format to another once download is complete. 

I don't need this, as this is expensive processing that can be done on another server. 

If this is what's happening, how can I disable it?

**Comment by gatecrasher777** [comment]
The ffmpeg audio conversion should only happen if you specify container to be ```mp3``` or ```flac```. ```any``` should just give the original audio file.

```sSheoMl5_uQ_audio_a0.mp4``` is a temporary audio file which should then be renamed ```sSheoMl5_uQ.aac``` when the download is complete. 

I will see if I can replicate the issue, and report back.

**Comment by gatecrasher777** [comment]
I was able to replicate the issue and have fixed it. 
It was recoding 'opus' and 'aac' where the intention was to make a fast stream copy.
I will put through a PR tomorrow as I have some other updates to complete first.
