### ISSUE TITLE
Same cookie on different IP addresses (question)

### ISSUE THREAD

**Issue by r0hin** [gatecrasher777/ytcog#34]
Do you know if a cookie will remain valid if it used on a whole bunch of different IP addresses to search and download videos?

**Comment by gatecrasher777** [comment]
I have used different VPNs with the same cookie - never had a problem. Also downloading from a different IP address from the IP address on which the stream was constructed.  Although original IP is in the stream URL, it doesn't seem to limit you provided n-transform and deciphering was originally done. That URL then works from any address.  That is my experience. Of course, things are always subject to change at any time.

**Comment by r0hin** [comment]
Alright, that's perfect then.

> Also downloading from a different IP address from the IP address on which the stream was constructed. Although original IP is in the stream URL, it doesn't seem to limit you provided n-transform and deciphering was originally done. That URL then works from any address.

Are you sure about this? Is this new behavior? I remember having a lot of trouble with this limitation.

**Comment by gatecrasher777** [comment]
I'm sure in the sense that my current work-in-progress project ytzero stores streams in a db (and primarily use low quality video streams for multiple preview purposes). If I switch to using a VPN (from various countries) they continue to work seemlessly. And this from inside HTML video tags in the browser using <source> as the ytcog processed stream URLs.  And if I want a high quality download of a specific video using the same set of stored streams these work too via the VPN.  You have about 5 hours 50 minutes before the streams expire.  

I only noticed this behaviour (the relaxation of IP restraints) after the n transform was introduced. I remember in the past you had to be coming from the same IP subnet for stream URLs to work.  It seems now that if you have correctly transformed the n parameter you are good to go.

**Comment by r0hin** [comment]
I seem to be facing a 403 error when trying to playback tracks from a different IP address. See if this video works for you: https://www.youtube.com/watch?v=4FqGpT3yhUI.

Anything I might be missing?

**Comment by gatecrasher777** [comment]
Just clicking the URL: 
VPN in France says "video is not available". 
ISP in South Africa plays fine.

So 403 looks like a regional copyright restriction.

**Comment by r0hin** [comment]
That's really strange. It gets generated in US central but I'm unable to play it here in Canada where it should be available. 

This happens with every auto-generated music video like that. Haven't tested normal videos though.
