### ISSUE TITLE
Can not get session again!

### ISSUE THREAD

**Issue by trantrung22** [gatecrasher777/ytcog#38]
Today, I again got the Session error: 'No information received'
Could u pls check it?

**Comment by gatecrasher777** [comment]
Can replicate.  Working on it.

**Comment by SirXavierC** [comment]
Close character within a regex but not within quotes is causing the issue. Quick fix in #39 but a more generic regex detector is needed long term.

**Comment by gatecrasher777** [comment]
Thanks for PR,  SirXavier.  I also did a PR but with an added safeguard that it cannot close the function block within an array. Merged.
Still, I'm sure Youtube will find something else to throw at us.

**Comment by SirXavierC** [comment]
No problem. There probably is a super robust solution but then the goalposts will no doubt be moved.

**Comment by trantrung22** [comment]
> Thanks for PR, SirXavier. I also did a PR but with an added safeguard that it cannot close the function block within an array. Merged. Still, I'm sure Youtube will find something else to throw at us.

You are right, It's just happen again
