### ISSUE TITLE
No media available

### ISSUE THREAD

**Issue by trantrung22** [gatecrasher777/ytcog#44]
Failed to get videoStreams for some video
Available media streams: { error: 'No media available' }

Sample Video ID: 4fndeDfaWCg
Command: node examples/video_test 4fndeDfaWCg

**Comment by gatecrasher777** [comment]
Please check if new release v2.4.1 fixes this issue. Worked for me.

**Comment by trantrung22** [comment]
> Please check if new release v2.4.1 fixes this issue. Worked for me.

It's works, thank you 🙏
