### ISSUE TITLE
Wrong video time properties

### ISSUE THREAD

**Issue by Hjaelp** [gatecrasher777/ytcog#5]
I'm having an issue with the 'updated', 'published' and 'isLive' properties. If I try to get this from a channel that has a regular video:
```
console.log("updated:", channel.videos[0].updated);
console.log("published:", channel.videos[0].published);
console.log("isLive:", channel.videos[0].isLive)
```

I get:
```
updated: 0
published: 1568813855500
isLive: false
```

a little while later but same video:
```
updated: 0
published: 1568814231378
isLive: false
```

Every video I tried the timestamp keeps changing, and updated is always 0.

For live videos, I get the following:
```
updated: 0
published: 0
duration: 0
isLive: false
```

But it's not as big of a deal, because I consider it live if duration is 0.

**Comment by gatecrasher777** [comment]
Thanks for raising this.  When you get video results from a channel or a search, the best that youtube provides with regards to a published time is some statement of age like "5 hours ago" or "3 months ago" which is converted into a rough published timestamp. Video results from a playlist have no indication of published time at all. 

If you then proceed to do a video.fetch() youtube then provides a published date, but not a time.  However if there are media streams available, those streams are all timestamped, and so the earliest timestamp becomes the published time for the video. That is about as accurate and reliable as it gets for published date/time, and should give consistent values. 

isLive is always false - unless you do a video.fetch() on a live event, then you should get isLive: true.  

updated will remain at 0 until you do a video.fetch(). Basically, updated is a timestamp of when you last did a video.fetch(). 

So I think the idea here is that you should do a video.fetch() on specific channel or search results to get the fullest possible information about a video.

**Comment by Hjaelp** [comment]
Thanks. That explains it.

**Comment by Hjaelp** [comment]
@gatecrasher777 is it possible to get this text timestamp that youtube uses for channel videos before fetch(), or do I have to calculate it myself?

**Comment by gatecrasher777** [comment]
For channel videos, if you run video.info() you will get something like this:

```js
    {
      "type": "video",
      "debugOn": false,
      "id": "UoHEvzQc0O4",
      "channelId": "UCG5qGWdu8nIRZqJ_GgDwQ-w",
      "duration": 14,
      "views": 49597,
      "published": "1m0w ago",
      "canEmbed": true,
      "isLive": false,
      "title": "Who scored the better penalty? | Italy v England | Euro 2020 Final",
      "author": "Premier League",
      "channelThumb": "https://yt3.ggpht.com/ytc/AKedOLRQp9LGTGsRZorAesLGLzLXwjZEPauJlRs0_GS-=s900-c-k-c0x00ffffff-no-rj",
      "country": "United Kingdom"
    },
```

So channel.video[i].info().published will give you something very similar to the youtube string.  It would fairly trivial to create another property to give the exact youtube string.  It is just that if the string was "3 minutes ago" it would only be valid for one minute, whereas info().published is dynamic, so ten and a half minues later, info().published would report  "13m30s ago".
