### ISSUE TITLE
Could not extract player functions

### ISSUE THREAD

**Issue by trantrung22** [gatecrasher777/ytcog#56]
I've updated to latest version 2.5.0 but got error message: Could not extract player functions
Could you pls check

**Comment by gatecrasher777** [comment]
Yes, Youtube have thrown us a curve ball. Will try to locate and fix the problem today,

**Comment by gatecrasher777** [comment]
PR #57 should fix it. Released version 2.5.1 with the fix.

**Comment by trantrung22** [comment]
It's works, many thanks for your so fasssst fixing
