### ISSUE TITLE
Cannot run program

### ISSUE THREAD

**Issue by sclsj** [gatecrasher777/ytcog#9]
```
node examples/dl_test.js
Session status: NOK (Session data not found)
```
```
node --version
v13.13.0
```

**Comment by sclsj** [comment]
Also, it seems like `ytcog` does not use the `http_proxy` and `https_proxy` I set. I have to use a VPN to access YouTube, and setting http_proxy and https_proxy worked for `youtube-dl`. I have to use `Proxifier` to force `ytcog` to use proxy.

**Comment by gatecrasher777** [comment]
In your first edit: I see the error at #process() which requires node 14. But in recent versions I removed the private methods (#) so that ytcog could run on earlier versions of node.  Try again with the latest version of ytcog (do an >npm update  in project folder).

I will close this. But if you still can't run ytcog, reopen it.

**Comment by sclsj** [comment]
`npm install -g ytcog` initially stalls at ffmpeg download step, which I guess is due to my internet location, so I cloned this repo and tried on it. That caused the error in the first edit. I decided to try again later with VPN on, and the `npm` successfully finishes. The error in the first edit does not show up again.

**Comment by sclsj** [comment]
Also, is it possible to 
- set modified date of video file to

**Comment by gatecrasher777** [comment]
> * set modified date of video file to upload date

Yes, I could make this an option in ytcog-dl

> * add video description and statistics to video file metadata

You can already add the description with  
```
ytcog: { metadata : 'description' }
ytcog-dl:   --metadata description
```
I could accommodate ${templates} in the metadata text options  
```
{ metadata: 'author,title,description,views=${views}' }
ytcog-dl:  --metadata "views" "${views}"
```
> * add video description and other metadata to `xattr`

Seems to be platform specific. Will have to research this.

> * download comments
> * embed subtitles

Both are on the todo list.
